/********************************************************************
 *                                                                  *
 * THIS FILE IS PART OF THE OggVorbis SOFTWARE CODEC SOURCE CODE.   *
 * USE, DISTRIBUTION AND REPRODUCTION OF THIS LIBRARY SOURCE IS     *
 * GOVERNED BY A BSD-STYLE SOURCE LICENSE INCLUDED WITH THIS SOURCE *
 * IN 'COPYING'. PLEASE READ THESE TERMS BEFORE DISTRIBUTING.       *
 *                                                                  *
 * THE OggVorbis SOURCE CODE IS (C) COPYRIGHT 1994-2002             *
 * by the Xiph.Org Foundation http://www.xiph.org/                  *
 *                                                                  *
 ********************************************************************

 function: static codebooks autogenerated by huff/huffbuld
 last modified: $Id: floor_books.h,v 1.1.2.2 2002/06/27 07:05:54 xiphmont Exp $

 ********************************************************************/

#include "codebook.h"
static long _huff_lengthlist_line_1024x27_0sub0[] = {
	 7, 7, 8, 7, 8, 6, 8, 6, 9, 6, 9, 6, 9, 5, 9, 5,
	 9, 5,10, 5,10, 5,10, 5,10, 5,10, 5,10, 5,10, 5,
	11, 5,10, 5,10, 5, 9, 5, 9, 5, 8, 5, 8, 5, 8, 5,
	 8, 5, 8, 6, 8, 6, 8, 6, 8, 6, 8, 6, 8, 6, 8, 6,
	 8, 6, 8, 7, 9, 7, 9, 7, 9, 7, 8, 7, 9, 7, 9, 7,
	10, 8,10, 8, 9, 8,10, 9,10, 8,10, 9,10, 9,11, 9,
	11,10,11,10,11,10,11,11,12,11,11,11,12,12,13,11,
	13,11,13,12,14,13,15,14,14,15,16,16,15,15,15,13,
};

static static_codebook _huff_book_line_1024x27_0sub0 = {
	1, 128,
	_huff_lengthlist_line_1024x27_0sub0,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_1024x27_1sub0[] = {
	 3, 5, 5, 4, 5, 4, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5,
	 6, 5, 6, 5, 7, 5, 7, 5, 7, 5, 8, 5, 9, 5, 9, 5,
};

static static_codebook _huff_book_line_1024x27_1sub0 = {
	1, 32,
	_huff_lengthlist_line_1024x27_1sub0,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_1024x27_1sub1[] = {
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 9, 4, 9, 4, 9, 5, 9, 4,10, 4,10, 4, 9, 4, 9, 4,
	 8, 4, 8, 4, 8, 4, 8, 4, 7, 5, 7, 5, 6, 5, 8, 6,
	 8, 6, 6, 5, 9, 6,10, 8,10, 8,11, 9,11, 9,11, 9,
	12,10,11,10,11,10,13,11,13,11,14,12,14,14,14,16,
	14,19,14,16,14,17,15,19,14,14,15,18,18,18,18,18,
	18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
};

static static_codebook _huff_book_line_1024x27_1sub1 = {
	1, 128,
	_huff_lengthlist_line_1024x27_1sub1,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_1024x27_2sub0[] = {
	 1, 5, 5, 5, 5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 6, 5,
	 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9,10,10,
};

static static_codebook _huff_book_line_1024x27_2sub0 = {
	1, 32,
	_huff_lengthlist_line_1024x27_2sub0,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_1024x27_2sub1[] = {
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 3, 3, 4, 3, 4, 4, 4, 4, 5, 4, 5, 5, 6, 6, 6, 7,
	 7, 7, 7, 7, 7, 9, 7,14, 7,14, 8,14, 8,14, 8,14,
	 8,14, 8,14, 8,14, 9,14, 9,14, 8,14, 9,14, 9,14,
	10,14, 9,14, 9,12,10,14,12,14,13,14,14,14,14,14,
	14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,
	14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,
};

static static_codebook _huff_book_line_1024x27_2sub1 = {
	1, 128,
	_huff_lengthlist_line_1024x27_2sub1,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_1024x27_3sub1[] = {
	 0, 4, 5, 4, 4, 4, 4, 3, 5, 3, 5, 4, 5, 4, 5, 4,
	 5, 4,
};

static static_codebook _huff_book_line_1024x27_3sub1 = {
	1, 18,
	_huff_lengthlist_line_1024x27_3sub1,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_1024x27_3sub2[] = {
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 5, 4, 5, 4, 6, 4, 6, 4, 6, 4, 7, 4, 7, 4,
	 7, 5, 7, 5, 8, 5, 8, 5, 8, 5,10, 5,10, 5,10, 4,
	10, 3,
};

static static_codebook _huff_book_line_1024x27_3sub2 = {
	1, 50,
	_huff_lengthlist_line_1024x27_3sub2,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_1024x27_3sub3[] = {
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 8, 2, 8, 2, 9, 3, 9, 3, 9, 4, 8, 4,12, 5,
	11, 5,14, 6,15, 6,15, 7,15, 9,15,12,15,14,15,15,
	15,15,15,15,15,15,15,15,15,15,15,14,14,14,14,14,
	14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,
	14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,
};

static static_codebook _huff_book_line_1024x27_3sub3 = {
	1, 128,
	_huff_lengthlist_line_1024x27_3sub3,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_1024x27_4sub1[] = {
	 0, 4, 5, 4, 5, 4, 5, 3, 5, 3, 6, 3, 6, 3, 6, 4,
	 6, 4,
};

static static_codebook _huff_book_line_1024x27_4sub1 = {
	1, 18,
	_huff_lengthlist_line_1024x27_4sub1,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_1024x27_4sub2[] = {
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 3, 2, 4, 2, 5, 4, 5, 4, 6, 6, 6, 7, 7, 7,
	 7, 7, 7, 8, 8, 8, 9, 8, 9, 9, 9, 9, 9,10,10,11,
	10,11,
};

static static_codebook _huff_book_line_1024x27_4sub2 = {
	1, 50,
	_huff_lengthlist_line_1024x27_4sub2,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_1024x27_4sub3[] = {
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 3, 5, 3, 3, 3, 4, 4, 5, 4, 7, 5, 9, 7, 9,
	 9, 9, 6, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
	 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
	 9, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
	 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
};

static static_codebook _huff_book_line_1024x27_4sub3 = {
	1, 128,
	_huff_lengthlist_line_1024x27_4sub3,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_1024x27_class1[] = {
	 3, 4,11,10,10, 9,13,13, 2, 1, 9, 5, 7, 6,12,10,
};

static static_codebook _huff_book_line_1024x27_class1 = {
	1, 16,
	_huff_lengthlist_line_1024x27_class1,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_1024x27_class2[] = {
	 1, 2, 3, 5, 4, 7, 6, 7,
};

static static_codebook _huff_book_line_1024x27_class2 = {
	1, 8,
	_huff_lengthlist_line_1024x27_class2,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_1024x27_class3[] = {
	 2, 3, 2, 4, 5, 7, 8, 9,11,11,11,11,20,20,20,20,
	 5, 8, 8, 8, 7, 9,11,10,12,12,13,11,20,20,20,20,
	 9,13,12,13, 9,12,14,14,15,17,15,14,20,20,20,20,
	20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,
	 4, 7, 7, 8, 6, 9,11,11,12,12,14,12,20,20,20,20,
	 5, 8, 9,11, 6, 8,12,13,11,12,14,14,20,20,20,20,
	 8,12,14,17, 9,11,15,19,13,15,15,15,20,20,20,20,
	20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,
	 7,10,12,15, 8,11,13,20,14,14,16,20,20,20,20,20,
	 6, 9,12,16, 8,10,13,20,14,13,16,20,20,20,20,20,
	11,12,18,20,11,13,17,20,16,18,18,20,20,20,20,20,
	20,20,20,20,20,19,19,19,19,19,19,19,19,19,19,19,
	16,19,17,19,17,19,18,19,19,19,19,19,19,19,19,19,
	13,15,16,19,13,13,16,19,19,18,19,19,19,19,19,19,
	19,19,19,19,19,18,19,19,19,19,19,19,19,19,19,19,
	19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,
};

static static_codebook _huff_book_line_1024x27_class3 = {
	1, 256,
	_huff_lengthlist_line_1024x27_class3,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_1024x27_class4[] = {
	 1, 4, 8,14, 4, 6, 9,19, 9, 9,12,21,21,16,16,20,
	 2, 5, 8,17, 7, 7, 9,15,11,10,12,20,20,15,15,20,
	 5, 8,11,18, 8, 8,11,17,13,11,13,18,20,20,20,20,
	18,20,20,20,17,18,20,20,20,20,20,20,20,20,20,20,
};

static static_codebook _huff_book_line_1024x27_class4 = {
	1, 64,
	_huff_lengthlist_line_1024x27_class4,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x11_0sub0[] = {
	 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 6, 5, 5, 5, 6, 5,
	 6, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	 6, 6, 6, 7, 6, 7, 6, 7, 6, 7, 6, 7, 7, 8, 7, 8,
	 7, 8, 7, 8, 7, 8, 8, 9, 8, 9, 8, 9, 8,10, 8,10,
	 9,10, 9,11, 9,11,10,11,10,11,11,12,10,12,11,13,
	11,13,12,15,12,14,13,14,14,13,13,16,15,16,15,16,
	15,16,15,16,16,16,16,16,16,16,16,16,16,16,16,16,
	16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,15,
};

static static_codebook _huff_book_line_128x11_0sub0 = {
	1, 128,
	_huff_lengthlist_line_128x11_0sub0,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x11_1sub0[] = {
	 1, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6,
	 6, 6, 7, 6, 7, 6, 8, 6, 8, 7, 8, 7, 9, 7, 9, 7,
};

static static_codebook _huff_book_line_128x11_1sub0 = {
	1, 32,
	_huff_lengthlist_line_128x11_1sub0,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x11_1sub1[] = {
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 5, 3, 6, 3, 6, 4, 6, 4, 7, 4, 7, 4, 7, 4, 7, 4,
	 8, 5, 8, 5, 8, 5, 8, 5, 8, 5, 9, 6, 9, 6, 9, 6,
	10, 7,11, 8, 8, 8,10, 9,10, 9,12,10,11,12,11,13,
	13,13,12,13,13,13,13,13,13,13,13,13,13,13,13,13,
	13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,
	13,13,12,12,12,12,12,12,12,12,12,12,12,12,12,12,
};

static static_codebook _huff_book_line_128x11_1sub1 = {
	1, 128,
	_huff_lengthlist_line_128x11_1sub1,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x11_2sub1[] = {
	 0, 4, 5, 4, 5, 3, 6, 3, 6, 3, 6, 3, 7, 3, 8, 4,
	 8, 4,
};

static static_codebook _huff_book_line_128x11_2sub1 = {
	1, 18,
	_huff_lengthlist_line_128x11_2sub1,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x11_2sub2[] = {
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 5, 2, 6, 2, 6, 3, 7, 4, 7, 5, 7, 5, 7, 5,
	 9, 6, 6,10, 6,10, 6,10, 6,10, 6,10, 7,10, 8, 9,
	 7, 9,
};

static static_codebook _huff_book_line_128x11_2sub2 = {
	1, 50,
	_huff_lengthlist_line_128x11_2sub2,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x11_2sub3[] = {
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 6, 7, 4, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
	 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
	 7, 7, 7, 7, 7, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
};

static static_codebook _huff_book_line_128x11_2sub3 = {
	1, 128,
	_huff_lengthlist_line_128x11_2sub3,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x11_3sub1[] = {
	 0, 4, 4, 4, 4, 4, 4, 4, 4, 3, 5, 4, 5, 4, 5, 4,
	 5, 4,
};

static static_codebook _huff_book_line_128x11_3sub1 = {
	1, 18,
	_huff_lengthlist_line_128x11_3sub1,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x11_3sub2[] = {
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 5, 3, 6, 3, 6, 3, 7, 4, 8, 4, 8, 4, 9, 4,
	 9, 4,10, 4,10, 5,11, 5,11, 5,12, 5,11, 6,13, 6,
	13, 7,
};

static static_codebook _huff_book_line_128x11_3sub2 = {
	1, 50,
	_huff_lengthlist_line_128x11_3sub2,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x11_3sub3[] = {
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 6, 2, 7, 3, 7, 3, 7, 4, 7, 4, 8, 5, 7, 5,
	 7, 6, 8, 7, 7, 7, 6, 9, 6, 9, 6, 8, 7, 9, 6, 9,
	 6, 9, 7, 9, 7, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
	 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
	 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 8,
};

static static_codebook _huff_book_line_128x11_3sub3 = {
	1, 128,
	_huff_lengthlist_line_128x11_3sub3,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x11_class1[] = {
	 1, 5, 3, 7, 2, 7, 4, 6,
};

static static_codebook _huff_book_line_128x11_class1 = {
	1, 8,
	_huff_lengthlist_line_128x11_class1,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x11_class2[] = {
	 1,13,13,13, 4,11,11,13, 7,10, 7,13,13,13,10,13,
	 2,13,13,13, 6,13,13,13, 7,12, 7,13,13,13,11,13,
	 3,13,13,12, 9,12,12,12,12,12,10,12,12,12,12,12,
	12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,
};

static static_codebook _huff_book_line_128x11_class2 = {
	1, 64,
	_huff_lengthlist_line_128x11_class2,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x11_class3[] = {
	 7, 8,12,16, 6, 7,10,16,10,10,13,16,16,16,16,16,
	 3, 5, 8,16, 3, 4, 7,16, 6, 6, 8,16,16,16,13,15,
	 4, 6, 8,15, 2, 3, 5,15, 5, 5, 7,15,13,11,14,15,
	12,13,13,15, 8, 9,12,15, 9, 9,11,15,15,15,15,15,
};

static static_codebook _huff_book_line_128x11_class3 = {
	1, 64,
	_huff_lengthlist_line_128x11_class3,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x17_0sub0[] = {
	 5, 5, 5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5,
	 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	 6, 6, 6, 6, 6, 6, 7, 6, 7, 7, 7, 7, 7, 7, 7, 7,
	 7, 7, 8, 7, 8, 7, 8, 7, 8, 8, 8, 7, 9, 8, 9, 8,
	 9, 8,10, 8,10, 8,10, 8,10, 9,11, 9,11, 9,11, 9,
	12,10,12,10,12,11,13,12,13,12,14,13,14,14,16,14,
	18,16,19,16,18,17,19,17,19,18,19,19,19,19,19,19,
	19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,18,
};

static static_codebook _huff_book_line_128x17_0sub0 = {
	1, 128,
	_huff_lengthlist_line_128x17_0sub0,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x17_1sub0[] = {
	 2, 5, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
	 5, 6, 6, 6, 6, 6, 7, 6, 7, 6, 8, 7, 9, 7, 9, 7,
};

static static_codebook _huff_book_line_128x17_1sub0 = {
	1, 32,
	_huff_lengthlist_line_128x17_1sub0,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x17_1sub1[] = {
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 4, 2, 5, 3, 5, 3, 6, 4, 7, 4, 7, 4, 8, 5, 8, 5,
	 9, 6,11, 6,11, 6,11, 7,12, 8,14, 8,12, 9,13, 9,
	13,11,13,12,11,14,11,14,10,14,11,15,12,13,11,14,
	11,15,10,14,10,14,10,14,10,12, 9,12,10,14,11,15,
	11,13,11,15,12,15,14,15,14,14,15,15,15,15,15,15,
	15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,
};

static static_codebook _huff_book_line_128x17_1sub1 = {
	1, 128,
	_huff_lengthlist_line_128x17_1sub1,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x17_2sub1[] = {
	 0, 4, 5, 4, 5, 3, 5, 3, 6, 3, 7, 3, 8, 3, 9, 4,
	 9, 4,
};

static static_codebook _huff_book_line_128x17_2sub1 = {
	1, 18,
	_huff_lengthlist_line_128x17_2sub1,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x17_2sub2[] = {
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 8, 1, 8, 2, 8, 4, 9, 4,10, 5,11, 5,10, 6,
	11, 7, 9, 7,11, 9,12, 8, 9,12, 9,12,11,12,12,12,
	12,12,
};

static static_codebook _huff_book_line_128x17_2sub2 = {
	1, 50,
	_huff_lengthlist_line_128x17_2sub2,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x17_2sub3[] = {
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
	 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 6,
	 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
};

static static_codebook _huff_book_line_128x17_2sub3 = {
	1, 128,
	_huff_lengthlist_line_128x17_2sub3,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x17_3sub1[] = {
	 0, 4, 4, 4, 4, 4, 5, 4, 5, 3, 5, 3, 5, 4, 5, 4,
	 5, 4,
};

static static_codebook _huff_book_line_128x17_3sub1 = {
	1, 18,
	_huff_lengthlist_line_128x17_3sub1,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x17_3sub2[] = {
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 5, 3, 5, 3, 5, 4, 6, 4, 6, 4, 7, 4, 8, 4,
	 8, 4, 9, 4, 9, 5,10, 5,10, 5,10, 5,11, 6,12, 6,
	12, 7,
};

static static_codebook _huff_book_line_128x17_3sub2 = {
	1, 50,
	_huff_lengthlist_line_128x17_3sub2,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x17_3sub3[] = {
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 8, 1,10, 2, 9, 3,11, 4,12, 6,12, 6,12, 8,
	12, 9,12,10,12,12,12,12,12,12,12,12,12,12,12,12,
	12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,
	12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,
	12,12,12,12,12,12,12,12,12,12,12,11,11,11,11,11,
};

static static_codebook _huff_book_line_128x17_3sub3 = {
	1, 128,
	_huff_lengthlist_line_128x17_3sub3,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x17_class1[] = {
	 1, 4, 3, 7, 2, 6, 5, 7,
};

static static_codebook _huff_book_line_128x17_class1 = {
	1, 8,
	_huff_lengthlist_line_128x17_class1,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x17_class2[] = {
	 1,15,15,15, 2,12,14,15, 5,12,10,15,15,15,15,15,
	 3,15,15,15, 4,15,15,15, 6,15,13,15,15,15,15,15,
	 7,15,15,15, 8,15,15,15,12,15,15,15,15,15,15,15,
	14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,
};

static static_codebook _huff_book_line_128x17_class2 = {
	1, 64,
	_huff_lengthlist_line_128x17_class2,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x17_class3[] = {
	 1, 6,10,20, 5, 8,11,20,11,10,12,20,20,17,20,20,
	 3, 6, 9,19, 4, 6, 8,19, 9, 7,10,19,19,15,16,19,
	 4, 6, 8,19, 4, 5, 6,19, 8, 7, 8,19,19,14,15,19,
	13,13,14,19,10,10,11,19,13,11,13,19,19,19,19,19,
};

static static_codebook _huff_book_line_128x17_class3 = {
	1, 64,
	_huff_lengthlist_line_128x17_class3,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x4_0sub0[] = {
	 2, 2, 2, 2,
};

static static_codebook _huff_book_line_128x4_0sub0 = {
	1, 4,
	_huff_lengthlist_line_128x4_0sub0,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x4_0sub1[] = {
	 0, 0, 0, 0, 2, 2, 3, 3, 3, 3,
};

static static_codebook _huff_book_line_128x4_0sub1 = {
	1, 10,
	_huff_lengthlist_line_128x4_0sub1,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x4_0sub2[] = {
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 3, 4, 3, 4, 3,
	 4, 4, 4, 4, 5, 4, 5, 5, 5,
};

static static_codebook _huff_book_line_128x4_0sub2 = {
	1, 25,
	_huff_lengthlist_line_128x4_0sub2,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x4_0sub3[] = {
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 3, 4, 3, 5, 4,
	 5, 4, 6, 5, 6, 6, 7, 6, 8, 8, 8,10, 9,15, 9,15,
	 9, 9, 9,12,15,15,14,14,14,14,14,14,14,14,14,14,
};

static static_codebook _huff_book_line_128x4_0sub3 = {
	1, 64,
	_huff_lengthlist_line_128x4_0sub3,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x4_class0[] = {
	 8, 8, 8,12, 7, 7, 8,12, 6, 6, 6, 9,10, 9, 9,11,
	 9, 9, 9,13, 8, 8, 8,12, 7, 6, 7,10,10,11,10,13,
	10,10,10,12, 9, 9,10,12, 9, 8, 8,13,15,12,12,15,
	16,15,14,16,14,16,15,16,15,16,14,16,16,16,16,16,
	 8, 7, 7,10, 7, 7, 7,10, 6, 5, 6, 9,10, 9, 9,12,
	 8, 8, 8,11, 8, 7, 7,10, 6, 6, 6,10,10, 9, 9,12,
	 9, 9, 9,12, 9, 9, 9,11, 9, 8, 9,10,13,14,12,13,
	16,14,14,16,15,14,14,15,16,16,14,15,16,16,16,16,
	 8, 7, 6, 7, 6, 6, 5, 6, 5, 5, 5, 5,10, 9, 8,11,
	 8, 7, 6, 7, 7, 6, 5, 6, 6, 6, 5, 6,10, 9, 8,10,
	 9, 8, 7, 8, 9, 8, 6, 7, 8, 7, 5, 7,10,10, 9,10,
	13,12,11,14,12,12,11,14,12,11,10,11,16,16,13,14,
	11,10,10,11,10, 9, 9,11, 9, 9, 8, 8,10,10,10,15,
	11,11,10,12,10, 9, 9,11, 9, 8, 7,10,10,10,10,14,
	11,10,10,13,10, 9, 8,13, 9, 8, 7,12,11,10,11,16,
	14,13,11,16,13,13,11,16,14,16,11,14,16,16,15,15,
};

static static_codebook _huff_book_line_128x4_class0 = {
	1, 256,
	_huff_lengthlist_line_128x4_class0,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x7_0sub1[] = {
	 0, 4, 3, 4, 2, 4, 2, 4, 3,
};

static static_codebook _huff_book_line_128x7_0sub1 = {
	1, 9,
	_huff_lengthlist_line_128x7_0sub1,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x7_0sub2[] = {
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 4, 4, 4, 4, 4,
	 4, 4, 4, 4, 4, 5, 5, 5, 5,
};

static static_codebook _huff_book_line_128x7_0sub2 = {
	1, 25,
	_huff_lengthlist_line_128x7_0sub2,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x7_0sub3[] = {
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 4, 4, 5,
	 4, 5, 4, 5, 5, 5, 5, 6, 6, 7, 7,10, 7, 9, 9,14,
	10,12,11,14,12,14,14,14,14,14,14,14,14,13,13,13,
};

static static_codebook _huff_book_line_128x7_0sub3 = {
	1, 64,
	_huff_lengthlist_line_128x7_0sub3,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x7_1sub1[] = {
	 0, 2, 3, 3, 3, 3, 4, 3, 4,
};

static static_codebook _huff_book_line_128x7_1sub1 = {
	1, 9,
	_huff_lengthlist_line_128x7_1sub1,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x7_1sub2[] = {
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 3, 4, 3, 5, 3,
	 5, 3, 6, 4, 7, 4, 8, 5, 8,
};

static static_codebook _huff_book_line_128x7_1sub2 = {
	1, 25,
	_huff_lengthlist_line_128x7_1sub2,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x7_1sub3[] = {
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 5, 3, 5, 3, 6, 3,
	 6, 3, 7, 4, 8, 5, 9, 6, 9, 7, 9, 9,10,10, 9, 7,
	 8, 9,13,13,13,13,13,13,13,13,13,13,13,13,12,12,
};

static static_codebook _huff_book_line_128x7_1sub3 = {
	1, 64,
	_huff_lengthlist_line_128x7_1sub3,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x7_class0[] = {
	 9, 7, 6, 9,11, 8, 7,10,14,11, 9,10,16,16,16,16,
	 7, 4, 4, 6, 7, 4, 3, 6,11, 8, 7, 8,16,16,16,16,
	 9, 6, 5, 7, 6, 3, 2, 5,10, 7, 6, 7,16,16,15,15,
	15,11, 8, 9, 9, 6, 5, 7,13,11, 9, 8,16,16,16,16,
};

static static_codebook _huff_book_line_128x7_class0 = {
	1, 64,
	_huff_lengthlist_line_128x7_class0,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

static long _huff_lengthlist_line_128x7_class1[] = {
	 6,17,17,17,11,17,16,16,15,16,16,16,16,16,16,16,
	 5,16,16,16, 9,16,16,16,14,16,15,16,16,16,16,16,
	 8,16,16,16, 9,16,16,16,13,16,16,16,16,16,16,16,
	15,16,16,16,15,16,16,16,16,16,16,16,16,16,16,16,
	 3,16,16,16, 8,16,16,16,11,13,12,16,16,16,15,16,
	 2,16,16,16, 7,16,16,16, 9,14,12,16,16,16,14,16,
	 5,16,16,16, 7,16,16,16,11,16,13,16,16,16,16,16,
	13,16,16,16,12,16,16,16,16,16,15,16,16,16,16,16,
	 4,16,16,16, 8,16,16,16,10,13,12,16,16,16,15,16,
	 2,16,16,16, 5,16,16,16, 8,13,10,16,16,16,13,16,
	 4,16,16,16, 6,16,16,16, 8,14,11,16,16,16,11,16,
	11,16,16,16,10,16,16,16,14,16,13,16,16,16,13,16,
	 8,16,16,16,11,16,16,16,12,16,15,16,16,16,13,16,
	 5,16,16,16, 9,16,16,16, 9,16,14,16,16,16, 9,16,
	 6,16,16,16, 7,16,16,16, 9,16,11,16,16,16, 8,16,
	12,16,16,16,11,16,16,16,14,16,13,16,16,16,13,16,
};

static static_codebook _huff_book_line_128x7_class1 = {
	1, 256,
	_huff_lengthlist_line_128x7_class1,
	0, 0, 0, 0, 0,
	NULL,
	NULL,
	NULL,
	NULL,
	0
};

